from turtle import *
def triangle(color):
    fillcolor(color)
    begin_fill()
    pendown()
    forward(50)
    left(135)
    forward(71)
    left(135)
    forward(50)
    left(90)
    penup()
    end_fill()

def square(color):
    fillcolor(color)
    begin_fill()
    pendown()
    forward(50)
    right(90)
    forward(50)
    right(90)
    forward(50)
    right(90)
    forward(50)
    right(90)
    penup()
    end_fill()

def fiveangle(color):
    fillcolor(color)
    begin_fill()
    pendown()
    right(108)
    forward(50)
    left(72)
    forward(50)
    left(72)
    forward(50)
    left(72)
    forward(50)
    left(72)
    forward(50)
    penup()
    end_fill()

def sixangle(color):
    fillcolor(color)
    begin_fill()
    pendown()
    forward(40)
    right(60)
    forward(40)
    right(60)
    forward(40)
    right(60)
    forward(40)
    right(60)
    forward(40)
    right(60)
    forward(40)
    right(60)
    penup()
    end_fill()

def star(color):
    fillcolor(color)
    begin_fill()
    pendown()
    right(54)
    forward(27)
    left(54)
    forward(27)
    right(126)
    forward(27)
    left(54)
    forward(27)
    right(126)
    forward(27)
    left(54)
    forward(27)
    right(126)
    forward(27)
    left(54)
    forward(27)
    right(126)
    forward(27)
    left(54)
    forward(27)
    end_fill()

triangle(color="green")
penup()
left(180)
forward(20)
square("pink")
penup()
forward(80)
fiveangle("black")
penup()
right(90)
forward(25)
left(90)
backward(25)
sixangle("blue")
penup()
right(90)
forward(25)
left(90)
forward(90)
left(90)
forward(6)
right(90)
star("yellow")